name = "RandomTweaks"
uuid = "97e8ad84-0770-496d-b901-33f7e6c3230c"
authors = ["Ondrej Winter <ondrej.winter@fs.cvut.cz> and contributors"]
version = "0.1.1"

[deps]
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
QuadGK = "2.4"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
